name: 'Bump Semantic Version'
description: 'Bumps either major, minor, or patch of a semantic version. Only works for simple x.y.z versions.'
inputs:
  version:
    description: 'version in x.y.z format'
    required: true
  bump:
    description: 'major, minor, or patch'
    required: true
outputs:
  version:
    description: 'The bumped version'
runs:
  using: 'node16'
  main: 'dist/index.js'
